### ISSUE TITLE
Alias speech is skipped when a msg starts with parenthesis 

### ISSUE THREAD

**Issue by jonpoveda** [UltimateBrent/discord-rod#9]
Alias is not activated when you start a message with parenthesis.

Steps to reproduce:
- Set a server alias or a channel alias
- Send a message that starts with parenthesis

Expected: the message appears using the set alias

**Comment by UltimateBrent** [comment]
Thanks, this is actually intended, and a continuation from Rod1, but I'll be changing how it works. Right now, you can bypass rod by using a parenthesis to talk "out of character". 

Moving foward we'rell have `ignoreCharacters` that can be set per server, with `(` used a default. This should account for the desire to speak out of character as well as to ignore things like Avrae commands easily.
